import type { Metadata } from "next";
import "./globals.css";
import Header from "./component/Header/Header";
import Footer from "./component/Footer/Footer";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <header>
          <Header />
        </header>
        <main> {children}</main>
        <Toaster />
        <footer>
          <Footer />
        </footer>{" "}
      </body>
    </html>
  );
}
